name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set google-services.json
      run: echo "${GOOGLE_SERVICES_JSON}" > app/google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{secrets.GOOGLE_SERVICES_JSON}}
    - name: Build with Gradle
      run: ./gradlew build
    - name: upload artifact to Firebase App Distribution
      if: github.event_name == 'push'
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        file: app/build/outputs/apk/debug/app-debug.apk
        group: testers
    - name: Store test results
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: ./**/build/outputs/apk

